services:
  db:
    container_name: db
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: haneul1023!
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-uroot", "-pmysql"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    container_name: web
    build: .
    command: sh -c "python manage.py migrate --settings=KKaebiBack.settings.dev && python manage.py runserver 0.0.0.0:8000 --settings=KKaebiBack.settings.dev"
    environment:
      MYSQL_ROOT_PASSWORD: haneul1023!
      DATABASE_NAME: kkaebi
      DATABASE_USER: admin
      DATABASE_PASSWORD: KKaebi1230!
      DATABASE_PORT: 3306
      DATABASE_HOST: kkaebi.cp8qqww8q2ap.ap-northeast-2.rds.amazonaws.com
      DJANGO_SETTINGS_MODULE: KKaebiBack.settings.dev
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db

volumes:
  dbdata:
