# Generated by Django 4.2.7 on 2024-11-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housework', '0003_rename_house_housework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housework',
            name='houseworkDetail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='housework',
            name='houseworkDone',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='housework',
            name='houseworkPlace',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
