# Generated by Django 4.2.7 on 2024-11-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housework', '0005_alter_housework_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housework',
            name='tag',
        ),
        migrations.AddField(
            model_name='housework',
            name='tag',
            field=models.ManyToManyField(related_name='user_housework', to='Housework.houseworktag'),
        ),
    ]
