# Generated by Django 4.2.7 on 2024-11-22 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Housework', '0006_remove_housework_tag_housework_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housework',
            name='tag',
        ),
        migrations.AddField(
            model_name='housework',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_housework', to='Housework.houseworktag'),
        ),
    ]
