# Generated by Django 4.2.7 on 2024-11-22 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Housework', '0007_remove_housework_tag_housework_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housework',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_housework', to='Housework.houseworktag'),
        ),
    ]
