# Generated by Django 4.2.7 on 2024-11-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Housework', '0008_alter_housework_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housework',
            name='houseworkDone',
            field=models.BooleanField(default=False),
        ),
    ]
