# Generated by Django 4.2.7 on 2024-11-25 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calendarapp', '0001_initial'),
        ('Housework', '0009_alter_housework_houseworkdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='housework',
            name='calendar_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='housework_events', to='calendarapp.calendarevent'),
        ),
    ]
