# Generated by Django 4.2.7 on 2024-11-25 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_houseworktag_user_tag'),
        ('Housework', '0011_remove_housework_calendar_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housework',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_housework', to='User.houseworktag'),
        ),
        migrations.DeleteModel(
            name='HouseworkTag',
        ),
    ]
