# Generated by Django 4.2.7 on 2024-11-25 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_alter_user_tag'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Housework', '0012_alter_housework_tag_delete_houseworktag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housework',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_houseworktag', to='User.houseworktag'),
        ),
        migrations.AlterField(
            model_name='housework',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_houseworkuser', to=settings.AUTH_USER_MODEL),
        ),
    ]
