# Generated by Django 4.2.7 on 2024-11-25 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Housework', '0013_alter_housework_tag_alter_housework_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housework',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_housework', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='HouseworkTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('users', models.ManyToManyField(blank=True, related_name='housework_tags', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='housework',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_housework', to='Housework.houseworktag'),
        ),
    ]
