# Generated by Django 4.2.7 on 2024-11-24 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_alter_house_housecode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='house',
        ),
        migrations.AddField(
            model_name='user',
            name='house',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_house', to='User.house'),
        ),
    ]
