# Generated by Django 4.2.7 on 2024-11-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_remove_user_house_user_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('basic', '기본형'), ('premium', '프리미엄형')], default='basic', max_length=10),
        ),
    ]
