# Generated by Django 4.2.7 on 2024-11-25 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Housework', '0014_alter_housework_user_houseworktag_and_more'),
        ('User', '0007_alter_user_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tag',
        ),
        migrations.DeleteModel(
            name='HouseworkTag',
        ),
    ]
